name: Bug Report
description: Bug in c4p
title: "ðŸ› Bug Report: "
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: "
        Thanks for finding an issue and wanting to report it!

        You can open a [Pull Request](https://github.com/TheArqsz/containers4pentesters/pulls)."
  - type: textarea
    attributes:
      label: What are the details?
      description: Please provide as much info as possible.
      placeholder: >
        Please provide the context in which the problem occurred and explain what happened
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to happen
      description: What do you think went wrong?
      placeholder: >
        Please explain why you think the behaviour is incorrect. It is extremely helpful if you copy&paste
        the fragment of logs showing the exact error messages or wrong behaviour. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: >
        What are the exact steps to reproduce the problem? 
      placeholder: >
        Please make sure you provide a reproducible step-by-step case of how to reproduce the problem
        as minimally and precisely as possible. 
    validations:
      required: true