name: Feature Request
description: Submit a request for new feature
labels: ["type: feature request"]
body:
  - type: markdown
    attributes:
      value: "
        Thanks for having time to create this feature request!

        You can open a [Pull Request](https://github.com/amplication/amplication/pulls) immediately after."
  - type: textarea
    attributes:
      label: Feature description
      description: Describe new feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: What is the purpose of this feature?