name: Build and Publish

on:
  # push:
  #   branches: [feature/aircrack-ng]
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./tools/airbase-ng
            dockerfile: ./tools/airbase-ng/Dockerfile
            image: containers4pentesters/airbase-ng
          - context: ./tools/airdecap-ng
            dockerfile: ./tools/airdecap-ng/Dockerfile
            image: containers4pentesters/airdecap-ng
          - context: ./tools/airdecloak-ng
            dockerfile: ./tools/airdecloak-ng/Dockerfile
            image: containers4pentesters/airdecloak-ng
          - context: ./tools/aireplay-ng
            dockerfile: ./tools/aireplay-ng/Dockerfile
            image: containers4pentesters/aireplay-ng
          - context: ./tools/airmon-ng
            dockerfile: ./tools/airmon-ng/Dockerfile
            image: containers4pentesters/airmon-ng
          - context: ./tools/airodump-ng
            dockerfile: ./tools/airodump-ng/Dockerfile
            image: containers4pentesters/airodump-ng
          - context: ./tools/airolib-ng
            dockerfile: ./tools/airolib-ng/Dockerfile
            image: containers4pentesters/airolib-ng
          - context: ./tools/airserv-ng
            dockerfile: ./tools/airserv-ng/Dockerfile
            image: containers4pentesters/airserv-ng
          - context: ./tools/airtun-ng
            dockerfile: ./tools/airtun-ng/Dockerfile
            image: containers4pentesters/airtun-ng
          - context: ./tools/airventriloquist-ng
            dockerfile: ./tools/airventriloquist-ng/Dockerfile
            image: containers4pentesters/airventriloquist-ng

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_SECRET }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=schedule,pattern=latest
            type=sha
        
      - name: Extract metadata (tags, labels) for aircrack
        if: "contains(matrix.context, '-ng')"
        id: meta-aircrack
        uses: docker/metadata-action@v4
        with:
          images: containers4pentesters/aircrack-ng
          tags: |
            type=schedule,pattern=latest
            type=sha

      - name: Build and push aircrack.ng
        uses: docker/build-push-action@v3
        if: "contains(matrix.context, '-ng')"
        id: docker_build_aircrack
        with:
          context: ./tools/aircrack-ng
          file: ./tools/aircrack-ng/Dockerfile
          push: true
          tags: ${{ steps.meta-aircrack.outputs.tags }}
          labels: ${{ steps.meta-aircrack.outputs.labels }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        id: docker_build
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} ${{ steps.docker_build_aircrack.outputs.digest }}
