name: Verify pr branch c4p tools

on:
  push:
    branches:
      - '!main'

jobs:
  test-tools:
    runs-on: ubuntu-20.04
    env:
      DOCKER_NETWORK_TYPE: none
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
      - name: test-available-tools
        run: |
          $GITHUB_WORKSPACE/c4p.sh --fail