name: Verify c4p tools

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-tools:
    runs-on: ubuntu-20.04
    env:
      DOCKER_NETWORK_TYPE: none
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
      - name: list-available-tools
        run: |
          TOOLS_DIR="$GITHUB_WORKSPACE/tools"
          for tool in $(ls -1 $TOOLS_DIR/); do
            echo $tool
          done
      - name: test-available-tools
        run: |
          $GITHUB_WORKSPACE/c4p.sh --fail --verbose