name: Verify c4p tools

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-tools:
    runs-on: ubuntu-20.04
    env:
      DOCKER_NETWORK_TYPE: none
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
      - name: list-available-tools
        run: |
          $GITHUB_WORKSPACE/c4p.sh --list 
      - name: test-unexisting-tool
        run: |
          echo $( $GITHUB_WORKSPACE/c4p.sh --log-level 4 --tool unexisting 2>&1 || true ) | tee console.txt; \
          [ -s $GITHUB_WORKSPACE/console.txt ] && grep -q "unexisting" console.txt
      - name: test-logging-to-file
        run: |
          echo $( $GITHUB_WORKSPACE/c4p.sh --log-level 4 --log-file logs.txt --tool unexisting || true ) | tee console.txt; \
          [ -s $GITHUB_WORKSPACE/logs.txt ] && [ -s $GITHUB_WORKSPACE/console.txt ]
      - name: test-logging-only-to-file
        run: |
          echo $( $GITHUB_WORKSPACE/c4p.sh --log-level 4 --log-file logs.txt --only-log-file --tool unexisting || true ) | tee console.txt; \
          [ -s $GITHUB_WORKSPACE/logs.txt ] && ! [ -s $GITHUB_WORKSPACE/console.txt ]
      - name: test-available-tools
        run: |
          $GITHUB_WORKSPACE/c4p.sh --fail --log-level 4 