name: Verify Pull Request

on:
  pull_request:

env:
  TOOL_DIR: tools

jobs:
  pre-configure:
    runs-on: ubuntu-latest
    outputs:
      tools_matrix: ${{ steps.set-matrix.outputs.tools_matrix }}
    steps:
     - name: Checkout to repository
       uses: actions/checkout@v3
     - name: Set tools matrix data
       id: set-matrix
       run: echo "tools_matrix=$(jq -c . < ./tools.json)" >> $GITHUB_OUTPUT

  basic-test-tools:
    runs-on: ubuntu-20.04
    needs: pre-configure
    strategy:
      matrix: ${{ fromJson(needs.pre-configure.outputs.tools_matrix) }}
    env:
      DOCKER_NETWORK_TYPE: none
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
      - name: Test - check if proper files exist
        uses: andstor/file-existence-action@v3
        with:
          fail: true
          files: |
            ${{ env.TOOL_DIR }}/${{ matrix.tool_name }}/README.md, 
            ${{ env.TOOL_DIR }}/${{ matrix.tool_name }}/Dockerfile, 
            ${{ env.TOOL_DIR }}/${{ matrix.tool_name }}/test.sh
      - name: test-list-available-tools
        run: |
          $GITHUB_WORKSPACE/c4p.sh --list 
      - name: test-unexisting-tool
        run: |
          echo $( $GITHUB_WORKSPACE/c4p.sh --log-level 4 --tool unexisting || true ) | tee console.txt; \
          [ -s $GITHUB_WORKSPACE/console.txt ] && grep -q "unexisting" console.txt
      - name: test-logging-to-file
        run: |
          echo $( $GITHUB_WORKSPACE/c4p.sh --log-level 4 --log-file logs.txt --tool unexisting || true ) | tee console.txt; \
          [ -s $GITHUB_WORKSPACE/logs.txt ] && [ -s $GITHUB_WORKSPACE/console.txt ]
      - name: test-logging-only-to-file
        run: |
          echo $( $GITHUB_WORKSPACE/c4p.sh --log-level 4 --log-file logs.txt --only-log-file --tool unexisting || true ) | tee console.txt; \
          [ -s $GITHUB_WORKSPACE/logs.txt ] && ! grep -q '[^[:space:]]' $GITHUB_WORKSPACE/console.txt